# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
tasks:
  - init: >
      pyenv install --force 3.11 &&
      pyenv global 3.11 &&
      pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python # and commit this file to your remote git repository to share the goodness with others.
    - adamcowley.neo4j-vscode
    - gitpod.gitpod-remote-ssh
